### PR TITLE
A single gevent worker

### PR DESCRIPTION
**Pull request by nottrobin**
Also, pretty colours in talisker output.

QA
--

`./run`. See the pretty colours. Go to http://0.0.0.0:8035/, see it works.

### CODE REVIEW

**Comment by tbille** [comment]
This is not only pretty color.

**Comment by nottrobin** [comment]
wut?

**Comment by tbille** [comment]
ooooooooooooooooh I was just reading the descritpion not the title.

**Comment by jpmartinspt** [comment]
We should double check our usage of request.Session is thread-safe before making this happen and probably revisit certification.ubuntu.com too. https://github.com/psf/requests/issues/1871#issuecomment-454154020

**Comment by nottrobin** [comment]
@jpmartinspt could you explain what you mean? Requests gets monkey-patched by gevent, it's one of the main targets of gevent. What sort of thread unsafety are you worried about?

**Comment by nottrobin** [comment]
What would be an example of non-thread-safety?

@sowasred2012 ran into this error when implementing discourse-docs in multipass.run - https://github.com/gevent/gevent/issues/1016 - this could be the sort of thing you were talking about. But it was fixed simply by using the correct `talisker.gunicorn.gevent` as described in https://talisker.readthedocs.io/en/latest/gunicorn.html#python-3-6-async-and-requests

**Comment by jpmartinspt** [comment]
I have no particular worries, happened to have bumped into this thread a few days ago and some people seem to have issues with corrupt data when using threads together with Session. Maybe not an issue with greenlets.

**Comment by nottrobin** [comment]
That certainly sounds interesting - do you have a link?

**Comment by nottrobin** [comment]
@jpmartinspt From that same issue:

> Forget everything I said. I had a global variable (a dictionary) that should have been local. Requests is amazing.

I think maybe we don't need to worry about it.

**Review by jpmartinspt — APPROVED** [review]

**Pull request merged**
